name: Hello World
author: Caleb Wolfe
description: Greets someone
inputs:
  who-to-greet: 
    description: "Who to greet"
    required: true
    default: 'Lord Taco Supreme'
outputs:
  time:
    description: 'The time of gretting'

runs:
  using: 'node12'
  main: "dist/index.js"