on: push
jobs:
  testing-aciton:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/hello-action
        id: hello
        with:
          who-to-greet: "World-JS"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
      - uses: ./.github/actions/hello-docker
        id: hello-docker
        with:
          who-to-greet: "World-Docker"
      - run: |
          echo "Time: ${{ steps.hello-docker.outputs.time }}"
          echo $HELLO